Repository bobbyiliev/101-linux-commands-ebook, pull requests merged in 2021-10, with the labels that each got.

#5 mkdir command examples
  ebook/en/content/014-the-mkdir-command.md
Labels: hacktoberfest-accepted

#7 Added documantation for netstat command
  ebook/en/content/067-the-netstat-command.md
Labels: hacktoberfest-accepted

#8 Adding 001-the-ls-command.md contents
  ebook/en/content/001-the-ls-command.md
Labels: hacktoberfest-accepted

#11 added the clear command
  ebook/en/content/043-the-clear-command.md
Labels: hacktoberfest-accepted

#12 add history command, add chown command and update tail command
  README.md
  ebook/en/content/005-the-tail-command.md
  ebook/en/content/028-the-history-command.md
  ebook/en/content/101-the-chown-command.md
Labels: hacktoberfest-accepted

#13 Add uname command
  README.md
  ebook/en/content/013-the-uname-command.md
Labels: hacktoberfest-accepted

#15 Update 006-the-pwd-command.md
  ebook/en/content/006-the-pwd-command.md
Labels: hacktoberfest-accepted

#18 Add shutdown command
  README.md
  ebook/en/content/056-the-shutdown-command.md
Labels: hacktoberfest-accepted

#19 Add the man command
  README.md
  ebook/en/content/024-the-man-command.md
Labels: hacktoberfest-accepted

#20 Completed 054-the-zip-command
  ebook/en/content/054-the-zip-command.md
Labels: hacktoberfest-accepted

#21 Adding 040-the-rm-command.md contents
  ebook/en/content/040-the-rm-command.md
  ebook/en/content/043-the-clear-command.md
Labels: hacktoberfest-accepted

#24 Updated 006-the-pwd-command.md
  ebook/en/content/006-the-pwd-command.md
Labels: hacktoberfest-accepted

#28 Added first iteration of guidelines
  Guidelines.md
Labels: hacktoberfest-accepted

#27 awk and whereis command update
  ebook/en/content/090-the-awk-command.md
  ebook/en/content/096-the-whereis-command.md
Labels: hacktoberfest-accepted

#31 added lscpu command examples
  ebook/en/content/030-the-lscpu-command.md
Labels: hacktoberfest-accepted

#22 Added whoami command
  ebook/en/content/027-the-whoami-command.md
  ebook/en/content/056-the-shutdown-command.md
Labels: hacktoberfest-accepted

#29 added whoami command examples
  ebook/en/content/027-the-whoami-command.md
Labels: hacktoberfest-accepted

#32 ping command
  ebook/en/content/085-the-ping-command.md
Labels: hacktoberfest-accepted

#34 Added service command
  ebook/en/content/070-the-service-command.md
Labels: hacktoberfest-accepted

#30 cd command
  ebook/en/content/002-the-cd-command.md
Labels: hacktoberfest-accepted

#37 Added nano command
  README.md
  ebook/en/content/039-the-nano-command.md
Labels: hacktoberfest-accepted

#39 Update 017-the-who-command.md
  ebook/en/content/017-the-who-command.md
Labels: hacktoberfest-accepted

#41 Fix numbering in cd page
  ebook/en/content/002-the-cd-command.md
Labels: hacktoberfest-accepted

#46 updated the gzip command
  README.md
  ebook/en/content/015-the-gzip-command.md
Labels: hacktoberfest-accepted

#44 added the cp command (descriptively and neatly)
  ebook/en/content/031-the-cp-command.md
Labels: hacktoberfest-accepted

#45 Completed 055-the-unzip-command
  ebook/en/content/055-the-unzip-command.md
Labels: hacktoberfest-accepted

#53 Added sudo-command.
  README.md
  ebook/en/content/051-the-sudo-command.md
Labels: hacktoberfest-accepted

#55 add info about the mv command
  ebook/en/content/032-the-mv-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#60 added whois command
  ebook/en/content/088-the-whois-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#62 011-add-the-help-command
  ebook/en/content/011-the-help-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#65 Fixed typos in Guidelines.md
  Guidelines.md
Labels: hacktoberfest-accepted, ✔ fix typos

#66 Add Kill Command
  ebook/en/content/034-the-kill-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#69 025-add-the-passwd-command
  ebook/en/content/025-the-passwd-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#71 Adds the scp command
  ebook/en/content/076-the-scp-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#73 Adds the killall command
  README.md
  ebook/en/content/035-the-killall-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#75 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#76 Add guide about the du command.
  README.md
  ebook/en/content/084-the-du-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#61 added the information about the `echo` command
  README.md
  ebook/en/content/021-the-echo-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#77 Formatting improvements for rm and removal of TODO label
  README.md
  ebook/en/content/040-the-rm-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#79 Solution for Issue #78
  README.md
  ebook/en/content/010-the-df-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#63 Added cp command manual
  ebook/en/content/031-the-cp-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#80 Add info about the dir command
  ebook/en/content/057-the-dir-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#83 Adding 061-the-exit-command contents and remove its TODO from README.md file
  README.md
  ebook/en/content/061-the-exit-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#87 I have added the login command
  ebook/en/content/029-the-login-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#84 Updated sl and split commands
  ebook/en/content/012-the-factor-command.md
  ebook/en/content/020-the-sl-command.md
  ebook/en/content/078-the-split-command.md
Labels: hacktoberfest-accepted, 📚 new chapter, ✔ fix typos

#88 046-add-the-curl-command
  ebook/en/content/046-the-curl-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#85 fix grammar issues
  ebook/en/content/005-the-tail-command.md
Labels: hacktoberfest-accepted, ✔ fix typos

#81 remove cd .. - it doesn't return to previous directory, just lower
  ebook/en/content/002-the-cd-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#91 044-add-the-su-command
  ebook/en/content/044-the-su-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#97 Add bc command
  README.md
  ebook/en/content/009-the-bc-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#95 add nohup command chapter
  ebook/en/content/093-the-nohub-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#102 `lsof` command documentation added
  README.md
  ebook/en/content/068-the-lsof-command.md
Labels: documentation, hacktoberfest-accepted, 📚 new chapter

#100 Update examples in 009-the-bc-command.md
  ebook/en/content/009-the-bc-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#104 added description for ifconfig command
  README.md
  ebook/en/content/041-the-ifconfig-command.md
Labels: documentation, hacktoberfest-accepted, 📚 new chapter

#106 adding find and rmdir commands
  README.md
Labels: documentation, hacktoberfest-accepted

#108 Update 087-the-dig-command.md
  ebook/en/content/087-the-dig-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#109 Ps chapter
  README.md
  ebook/en/content/033-the-ps-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#107 added a description for hostname
  README.md
  ebook/en/content/038-the-hostname-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#111 Add env command
  README.md
  ebook/en/content/036-the-env-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#112 added tar command
  ebook/en/content/063-the-tar-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#115 Typo | Optimize kill command
  ebook/en/content/034-the-kill-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#116 Add the stat command
  README.md
  ebook/en/content/079-the-stat-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#117 Adds top/htop chapter
  README.md
  ebook/en/content/019-the-top-htop-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#119 added description for crontab
  README.md
  ebook/en/content/091-the-crontab-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#120 added description of xargs command
  README.md
  ebook/en/content/092-the-xargs-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#113 Added new chapter (wget)
  ebook/en/content/045-the-wget-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#122 Added 080-the-useradd-command
  ebook/en/content/080-the-useradd-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#128 added vmstat command
  ebook/en/content/071-the-vmstat-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#130 Added cut command manual
  ebook/en/content/098-the-cut-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#114 added description for wget command
  ebook/en/content/045-the-wget-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#131 Added rmdir command manual
  ebook/en/content/103-the-rmdir-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#132 Added additional options table for ps command
  ebook/en/content/033-the-ps-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#133 added printenv command
  ebook/en/content/037-the-printenv-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#136 add ip command
  ebook/en/content/042-the-ip-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#139 Add 099-sed-command manual
  ebook/en/content/099-the-sed-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#140 Update 082-the-usermod-command.md
  ebook/en/content/082-the-usermod-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#142 Added 074-uniq-command
  README.md
  ebook/en/content/074-the-uniq-command.md
Labels: documentation, hacktoberfest-accepted, 📚 new chapter

#145 Added the Linux lsblk command.
  README.md
  ebook/en/content/104-the-lsblk-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#146 Update 063-the-tar-command.md
  ebook/en/content/063-the-tar-command.md
Labels: hacktoberfest-accepted, ✨ improve existing chapter

#152 added last command
  ebook/en/content/048-the-last-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#155 Add 102-the-find-command.md
  ebook/en/content/102-the-find-command.md
Labels: hacktoberfest-accepted, 📚 new chapter

#279 removed extra comments from mkdocs
  mkdocs.yml
Labels: enhancement, hacktoberfest-accepted

#268 Add the xeyes command
  ebook/en/content/123-the-xeyes-command.md
Labels: ✨ improve existing chapter

#282 Added more examples to 041-the-ifconfig-command.md
  ebook/en/content/041-the-ifconfig-command.md
Labels: enhancement, hacktoberfest-accepted, ✨ improve existing chapter
